name: Trigger auto deployment for solid-demo-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/solid-demo-test-AutoDeployTrigger-230416e0-3507-4278-86c0-99bf673b25b2.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SOLIDDEMOTEST_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: soliddemo.azurecr.io
          registryUsername: ${{ secrets.SOLIDDEMOTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SOLIDDEMOTEST_REGISTRY_PASSWORD }}
          containerAppName: solid-demo-test
          resourceGroup: RG-AppTest
          imageToBuild: soliddemo.azurecr.io/solid-demo-test:${{ github.sha }}
          dockerfilePath: Dockerfile

     

